RegisterNetEvent("msh-hack-city:server:black" ,function ()
           exports["qb-weathersync"]:setBlackout(true)
end)
RegisterNetEvent("msh-hack-city:server:blacknotvisible",function ()
        exports["qb-weathersync"]:setBlackout(false)
end)
